### ISSUE TITLE
Vulnerability to call depth attack

### ISSUE THREAD

**Issue by yaronvel** [Dexaran/ECNS#1]
I would like to report vulnerability to call depth attack of `setBalance` [function](https://github.com/Dexaran/ECNS/blob/test/HashRegistrar.sol#L67).

The attack could cause the owner of a name that is invalidated in `invalidateName` to lose everything (rather then get half of deposit).

For the attack to happen the attacker should call `invalidateName` after invoking 1022 contracts (i.e., at call depth 1022).
The call to Deed contract will be depth 1023, and therefore the send operation will silently fail.

You can read more on the call depth attack [here](https://ethereum.stackexchange.com/questions/6150/how-does-the-stack-depth-attack-make-a-send-silently-fail).

Back then I reported it also to ENS project.
But they responded that call depth attack is no longer applicable in ETH due to [EIP 150](https://ethereum.stackexchange.com/questions/9398/how-does-eip-150-change-the-call-depth-attack).
However, this EIP was never implemented in ETC.

A possible fix is to do dummy call of depth 2 in `invalidateName` before calling set balance. If stack depth is 1022 then function will automatically throw.

`destoryDeed` is also vulnerability to this attack. However it is only called by `closeDeed`. And `closeDeed` preforms one send operation (and throw on failure) if before calling `destroyDeed`.

**Comment by pyskell** [comment]
At least for `parity` that doesn't seem to be correct, both Ethereum and Ethereum Classic are treated the same and differ at very few places in the code, most of it is just choosing which bootnodes to connect to and switching at ignoring the DAO fork

https://github.com/paritytech/parity/blob/51ef847c6461d50c5564960001ea1f12099ce3b9/CHANGELOG.md#upgrading-private-chain-specification-files

Reads:

> All the chain specification files now have EIP-150 rules enabled by default. To continue using the chain add the eip150Transition key under Engine/ethash/params and set it to a future transition block as shown in this example.

And the block EIP150 was enabled at is defined here: https://github.com/paritytech/parity/blob/a24b6ad983b9299d747133f105736779c141bcf7/ethcore/res/ethereum/classic.json

I haven't checked for other node software.

**Comment by pyskell** [comment]
This also looks like it was implemented in the ETC fork of `geth` according to this:
https://github.com/ethereumproject/ECIPs/blob/master/ECIPs/ECIP-1015.md

And here is the commit from @splix https://github.com/ethereumproject/go-ethereum/commit/ade15b947b2ebd4960380e6f5aa5690b58449527 and https://github.com/ethereumproject/go-ethereum/commit/2284da90cccf8f8af630d9336080ebaa892055fe

**Comment by yaronvel** [comment]
@pyskell is right. I stand corrected.
